### ISSUE TITLE
ESP8266 crashes in AP modus

### ISSUE THREAD

**Issue by hdaghigh** [lmirel/MorphingClockRemix#11]
After a DoubleReset switch the ESP to AP modus and stays until i try to connect my Phone to AP "MorphClk". At this time crashes ESP with an Exception (29) or Exception (28) and resets.
I use LOLIN Nodemcu ESP-12E. I tried also a WEMOS D1 mini but the problem remained. After compiling the code in Arduino IDE, I get a Warnuning about few available memory.

**Comment by lmirel** [comment]
I'm traveling lately and I din’t have much time for this.
I have experienced similar behavior. If you don’t care about wifi manager configuration, checkout my ‘no-wm’ branch and use manual configuration as explained in the code.
HTH

**Comment by lmirel** [comment]
I've pushed an update on master branch that should assist with this issue.
The problem seems to be related to the warning about low memory.
WiFi manager doesn't behave very well in these conditions.
Unfortunately, this means that weather icons should be disabled as they take most of the memory compared to basic functionality.

**Comment by hdaghigh** [comment]
Thank you very much for your reply. My investigations led me to the same result. I already deactivated the weather icons in my code to get a stable WiFi manager. Had anybody success at running the full code inc. icons and animations yet?

**Comment by lmirel** [comment]
it works fine if you don't need to configure WiFi, i.e. use the saved configurations.
it seems that WiFi Manager uses quite a bit of dynamic memory allocation and that fails due to little memory left.
