### ISSUE TITLE
Timezone always "0"

### ISSUE THREAD

**Issue by gadrecs** [lmirel/MorphingClockRemix#8]
Hi, i managed to get your version running. But whatever i do i cannot set the Timezone in the Webserver.
the value always stays at "0" 
I tried setting the value in the webserver with a "2" and a "+2" with no difference ..
Can you provide a hint what i am doing wrong ?

I wanted to set the timezone to Europe (Berlin) ....

Kind regards and many thanks !

**Comment by lmirel** [comment]
I use it with +2 so I know this works.
Your flash might need formatting. Can you check?

**Comment by gadrecs** [comment]
Hi, 

yes i checked and formatted.

After reloading the code it worked for 2 powerups

Plugging it all in the 3rd time the time was again set to 6 hrs ahead …

Really strange.

 

Many thanks in advance

 

Von: lmirel [mailto:notifications@github.com] 
Gesendet: Mittwoch, 24. Oktober 2018 10:12
An: lmirel/MorphingClockRemix <MorphingClockRemix@noreply.github.com>
Cc: Markus Pöschl <markus@poeschl.info>; Author <author@noreply.github.com>
Betreff: Re: [lmirel/MorphingClockRemix] Timezone always "0" (#8)

 

I use it with +1 so I know this works.
Your flash might need formatting. Can you check?

**Comment by UseAfterMe** [comment]
I am also have this exact issue for a while now.
I am -4 and no matter what zone I change it to I'm always 1 hour ahead of my current time.
I notice this happen after daylight savings and its SUPER frustrating.
I have formatted the board completely and still having this issue.

**Comment by UseAfterMe** [comment]
Is there a way to just hard code the time?
Having it always connect to an ntp server is not ideal at all especially if you lose wifi connection.

**Comment by gadrecs** [comment]
You would need a rtc-chip. The arduino board has no built in real time
clock module...

Am Mi., 19. Dez. 2018, 20:42 hat evilsperm <notifications@github.com>
geschrieben:

**Comment by UseAfterMe** [comment]
ahh makes sense ;)
Still something is wrong, I have tried to change it to ever time zone there is and it's always 1 hour ahead of my current time.

**Comment by UseAfterMe** [comment]
I finally got it to work, I had to set my time to -5 instead of -4 also need to use All Flash Contents.
It took me about 50+ flashes before it worked, not to unplug it a few times and see if it actually sticks.
Its very strange that ntp server cant even determine daylight saving...
Guess I will manually need to flash the device every time we change times ;(

**Comment by lmirel** [comment]
can you check your console output?
look for the following (in my case):
timezone=1

then look for the message:
Got NTP time: 09:47:21 12/12/2018

and see how it adapts.

you could copy/paste your whole output and I'll take a look.

**Comment by lmirel** [comment]
I experienced quite a few issues today on one setup due to flash issues.
I couldn't init the SPIFFS and all data configuration data was lost. I couldn't get the WiFi portal (WiFiManager) to work to set it up so I had to hardcode the settings just to get them saved properly.
weird stuff.. I think I'll give up the WiFi Manager in a future release and use predefined settings instead.

**Comment by lmirel** [comment]
If you don’t care about dynamic configuration via WiFi manager and the flash file system, checkout my ‘no-wm’ branch and configure your parameters statically as explained in the code.
HTH
